### ISSUE TITLE
Passing in an Animated.Value instead of config

### ISSUE THREAD

**Issue by paulxuca** [simonsteer/rn-animated-progress-circle#1]
Hi @simonsteer! 

Would you open to supporting passing in an Animated.Value instead of the configuration (https://github.com/simonsteer/rn-animated-progress-circle/blob/master/index.js#L14) to manage that inside the component?

Thanks a ton!

**Comment by simonsteer** [comment]
@paulxuca I've modified the component to optionally take an `Animated.Value` instead of a `Number` for the `percent` prop, which has been renamed to `value`

[take a look](https://github.com/simonsteer/rn-animated-progress-circle/commit/27cb5c7418881b81886d585eaf6e332d65216ed0)

Also updated prop documentation in the README to reflect these changes
